[package]
name = "redrs"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "redrs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"

[dependencies.redis]
version = "*"